apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deploy
  labels:
    app: nodejs
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1       
      maxUnavailable: 1  
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-container
        image: toqaabdalla/nodejs-helloworld:v2
        ports:
        - containerPort: 3000
